version: "3.9"
services:
  web:
    container_name: "python_app"
    build: ./python_dir
    ports:
      - "8000:5000"
    volumes:
      - ./python_dir/app:/app
    environment:
      FLASK_ENV: development
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    networks:
      - app_network

  mongodb:
    image: mongo:4.0-xenial
    container_name: "mongodb_python"
    restart: always
    ports: 
      - 27017:27017
    environment:
      DB_URL: mongodb//db/mymongo_dbd
    volumes: 
      - mymongo_db:/data/db
    networks:
      - app_network

volumes:
  mymongo_db:

networks:
  app_network:
    driver: bridge